
import { Category, Store, ThemeColor, AppFontSize } from './types';

export const DEFAULT_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Papeterie', iconName: 'Pencil' },
  { name: 'Electroménager', iconName: 'Tv' },
  { name: 'Informatique / multimédia', iconName: 'Laptop' },
  { name: 'Droguerie', iconName: 'SprayCan' },
  { name: 'Animalerie', iconName: 'Dog' },
  { name: 'Jardinage', iconName: 'Flower' },
  { name: 'Fournitures scolaires', iconName: 'Ruler' },
  { name: 'Bricolage', iconName: 'Hammer' },
  { name: 'Ustensiles de cuisine', iconName: 'Utensils' },
  { name: 'Vaisselle / Art de la table', iconName: 'CupSoda' },
  { name: 'Décoration', iconName: 'Lamp' },
  { name: 'Jouets', iconName: 'Gamepad2' },
  { name: 'Produits d’entretien', iconName: 'Sparkles' },
  { name: 'Apéritifs', iconName: 'Cookie' },
  { name: 'Boissons non alcoolisées', iconName: 'GlassWater' },
  { name: 'Boissons alcoolisées', iconName: 'Wine' },
  { name: 'Bio', iconName: 'Leaf' },
  { name: 'Produits en vrac / au poids', iconName: 'Scale' },
  { name: 'Boulangerie', iconName: 'Croissant' },
  { name: 'Hygiène / Santé', iconName: 'HeartPulse' },
  { name: 'Matières premières', iconName: 'Wheat' },
  { name: 'Vêtements', iconName: 'Shirt' },
  { name: 'Gâteaux', iconName: 'CakeSlice' },
  { name: 'Petit déjeuné', iconName: 'Coffee' },
  { name: 'Thé / café', iconName: 'CupSoda' },
  { name: 'Condiments', iconName: 'Pepper' },
  { name: 'Produits du monde', iconName: 'Globe' },
  { name: 'Puériculture', iconName: 'Baby' },
  { name: 'Alimentation sèche', iconName: 'Box' },
  { name: 'Conserves', iconName: 'Cylinder' },
  { name: 'Confiserie', iconName: 'Candy' },
  { name: 'Fruits / légumes', iconName: 'Apple' },
  { name: 'Laiterie', iconName: 'Milk' },
  { name: 'Crémerie / Fromagerie', iconName: 'Cheese' },
  { name: 'Surgelés', iconName: 'Snowflake' },
  { name: 'Asiatique / Japonais', iconName: 'Chopsticks' },
  { name: 'Pause déjeuné', iconName: 'Sandwich' },
  { name: 'Traiteur', iconName: 'ChefHat' },
  { name: 'Charcuterie', iconName: 'Sausage' },
  { name: 'Boucherie', iconName: 'Beef' },
  { name: 'Poissonnerie', iconName: 'Fish' },
  { name: 'Produits frais industriels', iconName: 'Package' },
  { name: 'Sport / Loisirs', iconName: 'Dumbbell' },
  { name: 'Véhicules (Auto / moto)', iconName: 'Car' },
];

export const DEFAULT_INITIAL_PRODUCTS = [
  { name: 'Lentilles', categoryName: 'Alimentation sèche', unit: 'boite(s)' },
  { name: 'Pâtes', categoryName: 'Alimentation sèche', unit: 'paquet(s)' },
  { name: 'Riz', categoryName: 'Alimentation sèche', unit: 'boite(s)' },
  { name: 'Croquettes', categoryName: 'Animalerie', unit: 'sac(s)' },
  { name: 'Jouet', categoryName: 'Animalerie', unit: 'article(s)' },
  { name: 'Anti-puces', categoryName: 'Animalerie', unit: 'Aucune' },
  { name: 'Sushis', categoryName: 'Asiatique / Japonais', unit: 'boite(s)' },
  { name: 'Rouleaux de printemps', categoryName: 'Asiatique / Japonais', unit: 'paquet(s)' },
  { name: 'Riz cantonais', categoryName: 'Asiatique / Japonais', unit: 'barquette(s)' },
  { name: 'Galettes de riz', categoryName: 'Bio', unit: 'sachet(s)' },
  { name: 'Graines de chia', categoryName: 'Bio', unit: 'sachet(s)' },
  { name: 'Vin rouge', categoryName: 'Boissons alcoolisées', unit: 'bouteille(s)' },
  { name: 'Bière', categoryName: 'Boissons alcoolisées', unit: 'pack(s)' },
  { name: 'Whisky', categoryName: 'Boissons alcoolisées', unit: 'bouteille(s)' },
  { name: 'Jus d’orange', categoryName: 'Boissons non alcoolisées', unit: 'bouteille(s)' },
  { name: 'Coca-Cola light', categoryName: 'Boissons non alcoolisées', unit: 'pack(s)' },
  { name: 'Jus de pomme', categoryName: 'Boissons non alcoolisées', unit: 'bouteille(s)' },
  { name: 'Côte de bœuf', categoryName: 'Boucherie', unit: 'pièce(s)' },
  { name: 'Poulet entier', categoryName: 'Boucherie', unit: 'pièce(s)' },
  { name: 'Steak haché', categoryName: 'Boucherie', unit: 'pièce(s)' },
  { name: 'Baguette', categoryName: 'Boulangerie', unit: 'article(s)' },
  { name: 'Croissants', categoryName: 'Boulangerie', unit: 'sachet(s)' },
  { name: 'Brioche', categoryName: 'Boulangerie', unit: 'article(s)' },
  { name: 'Vis', categoryName: 'Bricolage', unit: 'sachet(s)' },
  { name: 'Prise électrique', categoryName: 'Bricolage', unit: 'article(s)' },
  { name: 'Tournevis', categoryName: 'Bricolage', unit: 'article(s)' },
  { name: 'Pâté en croûte', categoryName: 'Charcuterie', unit: 'morceau(x)' },
  { name: 'Terrine de campagne', categoryName: 'Charcuterie', unit: 'morceau(x)' },
  { name: 'Boudin noir aux oignons', categoryName: 'Charcuterie', unit: 'g' },
  { name: 'Sel', categoryName: 'Condiments', unit: 'boite(s)' },
  { name: 'Poivre', categoryName: 'Condiments', unit: 'sachet(s)' },
  { name: 'Moutarde', categoryName: 'Condiments', unit: 'pot(s)' },
  { name: 'Ketchup', categoryName: 'Condiments', unit: 'tube(s)' },
  { name: 'Curry', categoryName: 'Condiments', unit: 'flacon(s)' },
  { name: 'Beurre', categoryName: 'Crémerie / Fromagerie', unit: 'plaquette(s)' },
  { name: 'Crème fraîche solide', categoryName: 'Crémerie / Fromagerie', unit: 'pot(s)' },
  { name: 'Lampe', categoryName: 'Décoration', unit: 'article(s)' },
  { name: 'Cadre de tableau', categoryName: 'Décoration', unit: 'article(s)' },
  { name: 'Allumettes', categoryName: 'Droguerie', unit: 'boite(s)' },
  { name: 'Bougie', categoryName: 'Droguerie', unit: 'article(s)' },
  { name: 'Cafetière', categoryName: 'Electroménager', unit: 'article(s)' },
  { name: 'Grille pain', categoryName: 'Electroménager', unit: 'article(s)' },
  { name: 'Stylos', categoryName: 'Fournitures scolaires', unit: 'sachet(s)' },
  { name: 'Cahier', categoryName: 'Fournitures scolaires', unit: 'article(s)' },
  { name: 'Feuilles', categoryName: 'Fournitures scolaires', unit: 'paquet(s)' },
  { name: 'Courgette', categoryName: 'Fruits / légumes', unit: 'pièce(s)' },
  { name: 'Tomates', categoryName: 'Fruits / légumes', unit: 'kg' },
  { name: 'Céleris', categoryName: 'Fruits / légumes', unit: 'branche(s)' },
  { name: 'Chips (petit sachet)', categoryName: 'Apéritifs', unit: 'sachet(s)' },
  { name: 'Cacahuètes', categoryName: 'Apéritifs', unit: 'sachet(s)' },
  { name: 'Olives', categoryName: 'Apéritifs', unit: 'barquette(s)' },
  { name: 'Mars', categoryName: 'Confiserie', unit: 'paquet(s)' },
  { name: 'Sucettes', categoryName: 'Confiserie', unit: 'sachet(s)' },
  { name: 'Haricots verts', categoryName: 'Conserves', unit: 'boite(s)' },
  { name: 'Petits pois', categoryName: 'Conserves', unit: 'boite(s)' },
  { name: 'Cœur de palmier', categoryName: 'Conserves', unit: 'boite(s)' },
  { name: 'Shampoing', categoryName: 'Hygiène / Santé', unit: 'tube(s)' },
  { name: 'Déodorant', categoryName: 'Hygiène / Santé', unit: 'article(s)' },
  { name: 'Gel douche', categoryName: 'Hygiène / Santé', unit: 'tube(s)' },
  { name: 'Souris', categoryName: 'Informatique / multimédia', unit: 'unité(s)' },
  { name: 'Carte SD', categoryName: 'Informatique / multimédia', unit: 'unité(s)' },
  { name: 'Ficelle', categoryName: 'Jardinage', unit: 'unité(s)' },
  { name: 'Graines de radis', categoryName: 'Jardinage', unit: 'sachet(s)' },
  { name: 'Puzzle', categoryName: 'Jouets', unit: 'article(s)' },
  { name: 'Lait', categoryName: 'Laiterie', unit: 'pack(s)' },
  { name: 'Oeufs', categoryName: 'Laiterie', unit: 'boite(s)' },
  { name: 'Farine', categoryName: 'Matières premières', unit: 'sachet(s)' },
  { name: 'Sucre en poudre', categoryName: 'Matières premières', unit: 'boite(s)' },
  { name: 'Miel', categoryName: 'Matières premières', unit: 'pot(s)' },
  { name: 'Livre', categoryName: 'Papeterie', unit: 'article(s)' },
  { name: 'Carte postale', categoryName: 'Papeterie', unit: 'article(s)' },
  { name: 'Sandwich', categoryName: 'Pause déjeuné', unit: 'paquet(s)' },
  { name: 'Salade de lentilles', categoryName: 'Pause déjeuné', unit: 'barquette(s)' },
  { name: 'Biscottes', categoryName: 'Petit déjeuné', unit: 'paquet(s)' },
  { name: 'Avoine', categoryName: 'Petit déjeuné', unit: 'boite(s)' },
  { name: 'Sardine', categoryName: 'Poissonnerie', unit: 'kg' },
  { name: 'Crevettes', categoryName: 'Poissonnerie', unit: 'g' },
  { name: 'Saumon', categoryName: 'Poissonnerie', unit: 'morceau(x)' },
  { name: 'Bloc WC', categoryName: 'Produits d’entretien', unit: 'boite(s)' },
  { name: 'Nettoyant sol', categoryName: 'Produits d’entretien', unit: 'bidon(s)' },
  { name: 'Sauce soja', categoryName: 'Produits du monde', unit: 'bouteille(s)' },
  { name: 'Wraps', categoryName: 'Produits du monde', unit: 'sachet(s)' },
  { name: 'Céréales', categoryName: 'Produits en vrac / au poids', unit: 'g' },
  { name: 'Lessive', categoryName: 'Produits en vrac / au poids', unit: 'kg' },
  { name: 'Lardon', categoryName: 'Produits frais industriels', unit: 'barquette(s)' },
  { name: 'Jambon', categoryName: 'Produits frais industriels', unit: 'barquette(s)' },
  { name: 'Pâte feuilletée', categoryName: 'Produits frais industriels', unit: 'rouleau(x)' },
  { name: 'Lait en poudre bébé', categoryName: 'Puériculture', unit: 'boite(s)' },
  { name: 'Biberon', categoryName: 'Puériculture', unit: 'article(s)' },
  { name: 'Petit pot', categoryName: 'Puériculture', unit: 'pot(s)' },
  { name: 'Chaussures', categoryName: 'Sport / Loisirs', unit: 'article(s)' },
  { name: 'Vélo', categoryName: 'Sport / Loisirs', unit: 'article(s)' },
  { name: 'Haricots verts', categoryName: 'Surgelés', unit: 'sachet(s)' },
  { name: 'Pizza', categoryName: 'Surgelés', unit: 'pièce(s)' },
  { name: 'Glace', categoryName: 'Surgelés', unit: 'pot(s)' },
  { name: 'Café en grains', categoryName: 'Thé / café', unit: 'sachet(s)' },
  { name: 'Thé à la mure', categoryName: 'Thé / café', unit: 'boite(s)' },
  { name: 'Café en capsules', categoryName: 'Thé / café', unit: 'paquet(s)' },
  { name: 'Paella', categoryName: 'Traiteur', unit: 'kg' },
  { name: 'Couscous', categoryName: 'Traiteur', unit: 'kg' },
  { name: 'Louche', categoryName: 'Ustensiles de cuisine', unit: 'article(s)' },
  { name: 'Marmite', categoryName: 'Ustensiles de cuisine', unit: 'article(s)' },
  { name: 'Grande assiette', categoryName: 'Vaisselle / Art de la table', unit: 'pièce(s)' },
  { name: 'Verre à pied', categoryName: 'Vaisselle / Art de la table', unit: 'pièce(s)' },
  { name: 'Désodorisant', categoryName: 'Véhicules (Auto / moto)', unit: 'article(s)' },
  { name: 'Huile', categoryName: 'Véhicules (Auto / moto)', unit: 'bidon(s)' },
  { name: 'Chaussettes', categoryName: 'Vêtements', unit: 'article(s)' },
  { name: 'Caleçon', categoryName: 'Vêtements', unit: 'article(s)' },
];

export const DEFAULT_STORE_NAMES = [
  'Leclerc', 'Carrefour', 'Auchan', 'Super U', 'Intermarché', 'Monoprix', 'Lidl', 'Aldi'
];

export const DEFAULT_UNITS = [
    'Aucune',
    'article(s)',
    'barquette(s)', 
    'bâton(s)',
    'bidon(s)',
    'boite(s)', 
    'botte(s)',
    'bouteille(s)',
    'branche(s)',
    'brique(s)',
    'cl', 
    'colis(s)',
    'filet(s)', 
    'fiole(s)',
    'flacon(s)',
    'fut(s)',
    'g', 
    'kg', 
    'L', 
    'morceau(x)',
    'pack(s)',
    'paquet(s)', 
    'pièce(s)', 
    'plaquette(s)',
    'pot(s)',
    'rouleau(x)',
    'sac(s)',
    'sachet(s)',
    'tranche(s)',
    'tube(s)',
    'unité(s)'
];

export const ICONS_LIST = [
  'Apple', 'Banana', 'Beef', 'Beer', 'Book', 'Box', 'Briefcase', 'Brush', 'CakeSlice', 'Candy',
  'Car', 'Carrot', 'ChefHat', 'Cheese', 'Chopsticks', 'Cigarette', 'CircleDollarSign', 'Coffee', 'Cookie',
  'Croissant', 'CupSoda', 'Cylinder', 'Dog', 'Droplet', 'Dumbbell', 'Fish', 'Flower', 'Gamepad2', 'Gift',
  'GlassWater', 'Globe', 'Hammer', 'HeartPulse', 'Home', 'IceCream', 'Key', 'Lamp', 'Laptop',
  'Leaf', 'Lightbulb', 'Milk', 'Package', 'Paintbrush', 'Pencil', 'Pepper', 'Pizza', 'Plug',
  'Ruler', 'Sandwich', 'Sausage', 'Scale', 'Scissors', 'Shirt', 'ShoppingBasket', 'ShoppingCart',
  'Smartphone', 'Snowflake', 'Sparkles', 'SprayCan', 'Store', 'Sun', 'Thermometer', 'Tv',
  'Umbrella', 'Utensils', 'Wheat', 'Wine', 'Wrench', 'Baby'
];

// Palettes definitions
export const THEME_PALETTES: Record<ThemeColor, Record<number | string, string>> = {
  blue: { 50: '#eef2ff', 100: '#e0e7ff', 200: '#c7d2fe', 300: '#a5b4fc', 400: '#818cf8', 500: '#6366f1', 600: '#4f46e5', 700: '#4338ca', 800: '#3730a3', 900: '#312e81', 950: '#1e1b4b' },
  bordeaux: { 50: '#fff1f2', 100: '#ffe4e6', 200: '#fecdd3', 300: '#fda4af', 400: '#fb7185', 500: '#f43f5e', 600: '#e11d48', 700: '#be123c', 800: '#9f1239', 900: '#881337', 950: '#4c0519' },
  yellow: { 50: '#fffbeb', 100: '#fef3c7', 200: '#fde68a', 300: '#fcd34d', 400: '#fbbf24', 500: '#f59e0b', 600: '#d97706', 700: '#b45309', 800: '#92400e', 900: '#78350f', 950: '#451a03' },
  orange: { 50: '#fff7ed', 100: '#ffedd5', 200: '#fed7aa', 300: '#fdba74', 400: '#fb923c', 500: '#f97316', 600: '#ea580c', 700: '#c2410c', 800: '#9a3412', 900: '#7c2d12', 950: '#431407' },
  mauve: { 50: '#f5f3ff', 100: '#ede9fe', 200: '#ddd6fe', 300: '#c4b5fd', 400: '#a78bfa', 500: '#8b5cf6', 600: '#7c3aed', 700: '#6d28d9', 800: '#5b21b6', 900: '#4c1d95', 950: '#2e1065' },
  green: { 50: '#ecfdf5', 100: '#d1fae5', 200: '#a7f3d0', 300: '#6ee7b7', 400: '#34d399', 500: '#10b981', 600: '#059669', 700: '#047857', 800: '#065f46', 900: '#064e3b', 950: '#022c22' }
};

export const THEME_DISPLAY_DATA: Record<ThemeColor, { label: string, color: string }> = {
    blue: { label: 'Bleu', color: '#4f46e5' },
    bordeaux: { label: 'Bordeaux clair', color: '#e11d48' },
    yellow: { label: 'Jaune clair', color: '#d97706' },
    orange: { label: 'Orange clair', color: '#ea580c' },
    mauve: { label: 'Mauve clair', color: '#7c3aed' },
    green: { label: 'Vert clair', color: '#059669' },
};

export const FONT_SIZES: Record<AppFontSize, { label: string, value: string }> = {
  small: { label: 'Petite', value: '87.5%' },
  medium: { label: 'Moyenne', value: '100%' },
  large: { label: 'Grande', value: '115%' }
};

// --- TRANSLATIONS ---

export const TRANSLATIONS = {
  fr: {
    nav_lists: 'Listes',
    nav_categories: 'Rayons',
    nav_articles: 'Articles',
    nav_stores: 'Magasins',
    nav_settings: 'Param.',
    
    // Lists
    my_lists: 'Mes Listes',
    shopping: 'Courses',
    menus: 'Menus de la semaine',
    search_list: 'Rechercher une liste...',
    search_menu: 'Rechercher un menu...',
    random: 'Aléatoire',
    random_hint: 'Vous pourriez faire pour cette semaine',
    new_list: 'Nouvelle liste',
    new_menu: 'Nouveau menu',
    edit_list: 'Modifier la liste',
    edit_menu: 'Modifier le menu',
    list_name: 'Nom de la liste...',
    menu_name: 'Nom du menu',
    menu_placeholder: 'Ex: Semaine 12, Menu Printemps...',
    created_at: 'Créé le',
    start_shopping: 'Démarrer les courses',
    list_empty: 'La liste est vide.',
    add_items_below: 'Ajoutez des produits ci-dessous.',
    store: 'Magasin',
    
    // Items
    add_item: 'Ajouter un article...',
    create_item: 'Créer',
    new_article: 'Nouvel Article',
    name: 'Nom',
    aisle: 'Rayon',
    price: 'Prix',
    unit: 'Unité',
    note: 'Note',
    create_and_add: 'Créer et Ajouter',
    
    // Active Shopping
    remaining: 'restant(s)',
    done: 'Terminé !',
    congrats: 'Courses Terminées !',
    bravo: 'Bravo, vous avez tout trouvé.',
    clear_checked: 'Effacer les articles barrés',
    
    // Categories
    manage_categories: 'Rayons',
    new_category: 'Rayon',
    edit_category: 'Modifier un rayon',
    create_category: 'Créer un rayon',
    icon: 'Icône',
    choose_icon: 'Choisir une icône',
    
    // Stores
    manage_stores: 'Magasins',
    new_store: 'Magasin',
    store_name: 'Nom du magasin',
    favorite_store: 'Magasin favori',
    set_favorite: 'Définir comme favori',
    aisle_order: 'Ordre des rayons',
    add_aisle: '+ Ajouter rayon',
    delete_store_title: 'Supprimer le magasin ?',
    delete_store_confirm: 'Vous êtes sur le point de supprimer',
    delete_store_warning: 'liste(s) de courses associée(s) ser(ont) également supprimée(s).',
    remove_aisle_title: 'Retirer le rayon ?',
    remove_aisle_confirm: 'Voulez-vous retirer le rayon',
    change_fav_title: 'Changer de magasin favori ?',
    change_fav_confirm: 'Voulez-vous définir',
    
    // Articles Management
    manage_articles: 'Articles',
    search_article: 'Rechercher un article...',
    price_history: 'Historique des prix',
    trend: 'Tendance',
    
    // Units
    add_unit: 'Ajouter une unité',
    edit_unit: 'Modifier l\'unité',
    delete_unit: 'Supprimer l\'unité',
    unit_placeholder: 'ex: kg, litre, paquet...',
    delete_unit_confirm: 'Voulez-vous vraiment supprimer l\'unité',
    
    // Settings
    settings: 'Paramètres',
    dark_mode: 'Mode Sombre',
    theme_color: 'Couleur du thème',
    font_size: 'Taille de police',
    data: 'Données',
    export_backup: 'Exporter une sauvegarde',
    import_backup: 'Importer une sauvegarde',
    backup_desc: 'Le fichier .json contient toutes vos listes, articles, rayons et préférences.',
    restore_confirm: 'Confirmer la restauration',
    restore_warning: 'Attention : Cette action va effacer toutes les données actuelles de l\'application.',
    restore_btn: 'Restaurer les données',
    language: 'Langue',
    
    // General
    on: 'Activé',
    off: 'Désactivé',
    customize: 'Personnalisez l\'apparence',
    adjust_text: 'Ajustez la taille du texte',
    save_restore: 'Sauvegarde et restauration',
    cancel: 'Annuler',
    save: 'Enregistrer',
    validate: 'Valider',
    delete: 'Supprimer',
    remove: 'Retirer',
    confirm: 'Confirmer',
    delete_confirm: 'Supprimer ?',
    delete_irreversible: 'Cette action est irréversible.',
    sure_delete: 'Êtes-vous sûr de vouloir supprimer',
    unknown: 'Inconnu',
    ok: 'OK',
    lunch: 'Midi',
    dinner: 'Soir',
    starter: 'Entrée',
    main_dish: 'Plat principal',
    dessert: 'Dessert',
    nothing_planned: 'Rien de prévu',
    
    // Days
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
  },
  en: {
    nav_lists: 'Lists',
    nav_categories: 'Aisles',
    nav_articles: 'Items',
    nav_stores: 'Stores',
    nav_settings: 'Settings',
    
    // Lists
    my_lists: 'My Lists',
    shopping: 'Shopping',
    menus: 'Weekly Menus',
    search_list: 'Search a list...',
    search_menu: 'Search a menu...',
    random: 'Random',
    random_hint: 'You could cook this week',
    new_list: 'New List',
    new_menu: 'New Menu',
    edit_list: 'Edit List',
    edit_menu: 'Edit Menu',
    list_name: 'List name...',
    menu_name: 'Menu Name',
    menu_placeholder: 'Ex: Week 12, Spring Menu...',
    created_at: 'Created on',
    start_shopping: 'Start Shopping',
    list_empty: 'The list is empty.',
    add_items_below: 'Add items below.',
    store: 'Store',
    
    // Items
    add_item: 'Add an item...',
    create_item: 'Create',
    new_article: 'New Item',
    name: 'Name',
    aisle: 'Aisle',
    price: 'Price',
    unit: 'Unit',
    note: 'Note',
    create_and_add: 'Create & Add',
    
    // Active Shopping
    remaining: 'remaining',
    done: 'Done!',
    congrats: 'Shopping Complete!',
    bravo: 'Well done, you found everything.',
    clear_checked: 'Clear checked items',
    
    // Categories
    manage_categories: 'Aisles',
    new_category: 'Aisle',
    edit_category: 'Edit Aisle',
    create_category: 'Create Aisle',
    icon: 'Icon',
    choose_icon: 'Choose an icon',
    
    // Stores
    manage_stores: 'Stores',
    new_store: 'Store',
    store_name: 'Store Name',
    favorite_store: 'Favorite Store',
    set_favorite: 'Set as Favorite',
    aisle_order: 'Aisle Order',
    add_aisle: '+ Add Aisle',
    delete_store_title: 'Delete Store?',
    delete_store_confirm: 'You are about to delete',
    delete_store_warning: 'associated shopping list(s) will also be deleted.',
    remove_aisle_title: 'Remove Aisle?',
    remove_aisle_confirm: 'Do you want to remove aisle',
    change_fav_title: 'Change Favorite Store?',
    change_fav_confirm: 'Do you want to set',
    
    // Articles Management
    manage_articles: 'Items',
    search_article: 'Search an item...',
    price_history: 'Price History',
    trend: 'Trend',
    
    // Units
    add_unit: 'Add Unit',
    edit_unit: 'Edit Unit',
    delete_unit: 'Delete Unit',
    unit_placeholder: 'ex: kg, liter, pack...',
    delete_unit_confirm: 'Are you sure you want to delete unit',
    
    // Settings
    settings: 'Settings',
    dark_mode: 'Dark Mode',
    theme_color: 'Theme Color',
    font_size: 'Font Size',
    data: 'Data',
    export_backup: 'Export Backup',
    import_backup: 'Import Backup',
    backup_desc: 'The .json file contains all your lists, items, aisles, and settings.',
    restore_confirm: 'Confirm Restoration',
    restore_warning: 'Warning: This action will erase all current application data.',
    restore_btn: 'Restore Data',
    language: 'Language',
    
    // General
    on: 'On',
    off: 'Off',
    customize: 'Customize appearance',
    adjust_text: 'Adjust text size',
    save_restore: 'Backup and Restore',
    cancel: 'Cancel',
    save: 'Save',
    validate: 'Validate',
    delete: 'Delete',
    remove: 'Remove',
    confirm: 'Confirm',
    delete_confirm: 'Delete?',
    delete_irreversible: 'This action is irreversible.',
    sure_delete: 'Are you sure you want to delete',
    unknown: 'Unknown',
    ok: 'OK',
    lunch: 'Lunch',
    dinner: 'Dinner',
    starter: 'Starter',
    main_dish: 'Main Dish',
    dessert: 'Dessert',
    nothing_planned: 'Nothing planned',
    
    // Days
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
  }
};

// Maps for Default Data Translation
export const CATEGORY_TRANSLATIONS: Record<string, string> = {
  'Papeterie': 'Stationery',
  'Electroménager': 'Appliances',
  'Informatique / multimédia': 'Multimedia / IT',
  'Droguerie': 'Hardware / Drugstore',
  'Animalerie': 'Pets',
  'Jardinage': 'Gardening',
  'Fournitures scolaires': 'School Supplies',
  'Bricolage': 'DIY',
  'Ustensiles de cuisine': 'Kitchen Utensils',
  'Vaisselle / Art de la table': 'Tableware',
  'Décoration': 'Decoration',
  'Jouets': 'Toys',
  'Produits d’entretien': 'Cleaning Products',
  'Apéritifs': 'Appetizers',
  'Boissons non alcoolisées': 'Soft Drinks',
  'Boissons alcoolisées': 'Alcohol',
  'Bio': 'Organic',
  'Produits en vrac / au poids': 'Bulk / Weigh',
  'Boulangerie': 'Bakery',
  'Hygiène / Santé': 'Health / Beauty',
  'Matières premières': 'Baking / Raw',
  'Vêtements': 'Clothing',
  'Gâteaux': 'Cakes / Biscuits',
  'Petit déjeuné': 'Breakfast',
  'Thé / café': 'Tea / Coffee',
  'Condiments': 'Condiments',
  'Produits du monde': 'World Foods',
  'Puériculture': 'Baby',
  'Alimentation sèche': 'Dry Food',
  'Conserves': 'Canned Food',
  'Confiserie': 'Candy / Sweets',
  'Fruits / légumes': 'Produce',
  'Laiterie': 'Dairy',
  'Crémerie / Fromagerie': 'Cheese / Cream',
  'Surgelés': 'Frozen',
  'Asiatique / Japonais': 'Asian',
  'Pause déjeuné': 'Lunch Break',
  'Traiteur': 'Deli / Caterer',
  'Charcuterie': 'Cured Meats',
  'Boucherie': 'Butcher',
  'Poissonnerie': 'Seafood',
  'Produits frais industriels': 'Fresh Processed',
  'Sport / Loisirs': 'Sports / Leisure',
  'Véhicules (Auto / moto)': 'Automotive',
};

export const UNIT_TRANSLATIONS: Record<string, string> = {
  'Aucune': 'None',
  'article(s)': 'item(s)',
  'barquette(s)': 'tray(s)',
  'bâton(s)': 'stick(s)',
  'bidon(s)': 'can(s)',
  'boite(s)': 'box(es)',
  'botte(s)': 'bunch(es)',
  'bouteille(s)': 'bottle(s)',
  'branche(s)': 'stalk(s)',
  'brique(s)': 'carton(s)',
  'colis(s)': 'package(s)',
  'filet(s)': 'net(s)',
  'fiole(s)': 'vial(s)',
  'flacon(s)': 'bottle(s)',
  'fut(s)': 'keg(s)',
  'morceau(x)': 'chunk(s)',
  'pack(s)': 'pack(s)',
  'paquet(s)': 'pack(s)',
  'pièce(s)': 'piece(s)',
  'plaquette(s)': 'slab(s)',
  'pot(s)': 'jar(s)',
  'rouleau(x)': 'roll(s)',
  'sac(s)': 'bag(s)',
  'sachet(s)': 'packet(s)',
  'tranche(s)': 'slice(s)',
  'tube(s)': 'tube(s)',
  'unité(s)': 'unit(s)',
};

export const PRODUCT_TRANSLATIONS: Record<string, string> = {
  'Lentilles': 'Lentils',
  'Pâtes': 'Pasta',
  'Riz': 'Rice',
  'Croquettes': 'Kibble',
  'Jouet': 'Toy',
  'Anti-puces': 'Flea treatment',
  'Sushis': 'Sushi',
  'Rouleaux de printemps': 'Spring rolls',
  'Riz cantonais': 'Fried rice',
  'Galettes de riz': 'Rice cakes',
  'Graines de chia': 'Chia seeds',
  'Vin rouge': 'Red wine',
  'Bière': 'Beer',
  'Whisky': 'Whisky',
  'Jus d’orange': 'Orange juice',
  'Coca-Cola light': 'Diet Coke',
  'Jus de pomme': 'Apple juice',
  'Côte de bœuf': 'Rib steak',
  'Poulet entier': 'Whole chicken',
  'Steak haché': 'Ground beef',
  'Baguette': 'Baguette',
  'Croissants': 'Croissants',
  'Brioche': 'Brioche',
  'Vis': 'Screws',
  'Prise électrique': 'Power socket',
  'Tournevis': 'Screwdriver',
  'Pâté en croûte': 'Pie crust pâté',
  'Terrine de campagne': 'Country terrine',
  'Boudin noir aux oignons': 'Black pudding',
  'Sel': 'Salt',
  'Poivre': 'Pepper',
  'Moutarde': 'Mustard',
  'Ketchup': 'Ketchup',
  'Curry': 'Curry',
  'Beurre': 'Butter',
  'Crème fraîche solide': 'Thick cream',
  'Lampe': 'Lamp',
  'Cadre de tableau': 'Picture frame',
  'Allumettes': 'Matches',
  'Bougie': 'Candle',
  'Cafetière': 'Coffee maker',
  'Grille pain': 'Toaster',
  'Stylos': 'Pens',
  'Cahier': 'Notebook',
  'Feuilles': 'Paper sheets',
  'Courgette': 'Zucchini',
  'Tomates': 'Tomatoes',
  'Céleris': 'Celery',
  'Chips (petit sachet)': 'Chips (small bag)',
  'Cacahuètes': 'Peanuts',
  'Olives': 'Olives',
  'Mars': 'Mars bar',
  'Sucettes': 'Lollipops',
  'Haricots verts': 'Green beans',
  'Petits pois': 'Peas',
  'Cœur de palmier': 'Hearts of palm',
  'Shampoing': 'Shampoo',
  'Déodorant': 'Deodorant',
  'Gel douche': 'Shower gel',
  'Souris': 'Mouse',
  'Carte SD': 'SD Card',
  'Ficelle': 'String',
  'Graines de radis': 'Radish seeds',
  'Puzzle': 'Puzzle',
  'Lait': 'Milk',
  'Oeufs': 'Eggs',
  'Farine': 'Flour',
  'Sucre en poudre': 'Sugar',
  'Miel': 'Honey',
  'Livre': 'Book',
  'Carte postale': 'Postcard',
  'Sandwich': 'Sandwich',
  'Salade de lentilles': 'Lentil salad',
  'Biscottes': 'Rusks',
  'Avoine': 'Oats',
  'Sardine': 'Sardine',
  'Crevettes': 'Shrimp',
  'Saumon': 'Salmon',
  'Bloc WC': 'Toilet block',
  'Nettoyant sol': 'Floor cleaner',
  'Sauce soja': 'Soy sauce',
  'Wraps': 'Wraps',
  'Céréales': 'Cereal',
  'Lessive': 'Laundry detergent',
  'Lardon': 'Bacon bits',
  'Jambon': 'Ham',
  'Pâte feuilletée': 'Puff pastry',
  'Lait en poudre bébé': 'Baby formula',
  'Biberon': 'Baby bottle',
  'Petit pot': 'Baby jar',
  'Chaussures': 'Shoes',
  'Vélo': 'Bicycle',
  'Pizza': 'Pizza',
  'Glace': 'Ice cream',
  'Café en grains': 'Coffee beans',
  'Thé à la mure': 'Blackberry tea',
  'Café en capsules': 'Coffee capsules',
  'Paella': 'Paella',
  'Couscous': 'Couscous',
  'Louche': 'Ladle',
  'Marmite': 'Pot',
  'Grande assiette': 'Dinner plate',
  'Verre à pied': 'Wine glass',
  'Désodorisant': 'Air freshener',
  'Huile': 'Oil',
  'Chaussettes': 'Socks',
  'Caleçon': 'Boxers',
};
