
import { Category, Store, ThemeColor, AppFontSize } from './types';

export const DEFAULT_CATEGORIES: Omit<Category, 'id'>[] = [
  { name: 'Papeterie', iconName: 'Pencil' },
  { name: 'Electroménager', iconName: 'Tv' },
  { name: 'Informatique / multimédia', iconName: 'Laptop' },
  { name: 'Droguerie', iconName: 'SprayCan' },
  { name: 'Animalerie', iconName: 'Dog' },
  { name: 'Jardinage', iconName: 'Flower' },
  { name: 'Fournitures scolaires', iconName: 'Ruler' },
  { name: 'Bricolage', iconName: 'Hammer' },
  { name: 'Ustensiles de cuisine', iconName: 'Utensils' },
  { name: 'Vaisselle / Art de la table', iconName: 'CupSoda' },
  { name: 'Décoration', iconName: 'Lamp' },
  { name: 'Jouets', iconName: 'Gamepad2' },
  { name: 'Produits d’entretien', iconName: 'Sparkles' },
  { name: 'Apéritifs', iconName: 'Cookie' },
  { name: 'Boissons non alcoolisées', iconName: 'GlassWater' },
  { name: 'Boissons alcoolisées', iconName: 'Wine' },
  { name: 'Bio', iconName: 'Leaf' },
  { name: 'Produits en vrac / au poids', iconName: 'Scale' },
  { name: 'Boulangerie', iconName: 'Croissant' },
  { name: 'Hygiène / Santé', iconName: 'HeartPulse' },
  { name: 'Matières premières', iconName: 'Wheat' },
  { name: 'Vêtements', iconName: 'Shirt' },
  { name: 'Gâteaux', iconName: 'CakeSlice' },
  { name: 'Petit déjeuné', iconName: 'Coffee' },
  { name: 'Thé / café', iconName: 'CupSoda' },
  { name: 'Condiments', iconName: 'Pepper' },
  { name: 'Produits du monde', iconName: 'Globe' },
  { name: 'Puériculture', iconName: 'Baby' },
  { name: 'Alimentation sèche', iconName: 'Box' },
  { name: 'Conserves', iconName: 'Cylinder' },
  { name: 'Confiserie', iconName: 'Candy' },
  { name: 'Fruits / légumes', iconName: 'Apple' },
  { name: 'Laiterie', iconName: 'Milk' },
  { name: 'Crémerie / Fromagerie', iconName: 'Cheese' },
  { name: 'Surgelés', iconName: 'Snowflake' },
  { name: 'Asiatique / Japonais', iconName: 'Chopsticks' },
  { name: 'Pause déjeuné', iconName: 'Sandwich' },
  { name: 'Traiteur', iconName: 'ChefHat' },
  { name: 'Charcuterie', iconName: 'Sausage' },
  { name: 'Boucherie', iconName: 'Beef' },
  { name: 'Poissonnerie', iconName: 'Fish' },
  { name: 'Produits frais industriels', iconName: 'Package' },
  { name: 'Sport / Loisirs', iconName: 'Dumbbell' },
  { name: 'Véhicules (Auto / moto)', iconName: 'Car' },
];

export const DEFAULT_INITIAL_PRODUCTS = [
  { name: 'Lentilles', categoryName: 'Alimentation sèche', unit: 'boite(s)' },
  { name: 'Pâtes', categoryName: 'Alimentation sèche', unit: 'paquet(s)' },
  { name: 'Riz', categoryName: 'Alimentation sèche', unit: 'boite(s)' },
  { name: 'Croquettes', categoryName: 'Animalerie', unit: 'sac(s)' },
  { name: 'Jouet', categoryName: 'Animalerie', unit: 'article(s)' },
  { name: 'Anti-puces', categoryName: 'Animalerie', unit: 'Aucune' },
  { name: 'Sushis', categoryName: 'Asiatique / Japonais', unit: 'boite(s)' },
  { name: 'Rouleaux de printemps', categoryName: 'Asiatique / Japonais', unit: 'paquet(s)' },
  { name: 'Riz cantonais', categoryName: 'Asiatique / Japonais', unit: 'barquette(s)' },
  { name: 'Galettes de riz', categoryName: 'Bio', unit: 'sachet(s)' },
  { name: 'Graines de chia', categoryName: 'Bio', unit: 'sachet(s)' },
  { name: 'Vin rouge', categoryName: 'Boissons alcoolisées', unit: 'bouteille(s)' },
  { name: 'Bière', categoryName: 'Boissons alcoolisées', unit: 'pack(s)' },
  { name: 'Whisky', categoryName: 'Boissons alcoolisées', unit: 'bouteille(s)' },
  { name: 'Jus d’orange', categoryName: 'Boissons non alcoolisées', unit: 'bouteille(s)' },
  { name: 'Coca-Cola light', categoryName: 'Boissons non alcoolisées', unit: 'pack(s)' },
  { name: 'Jus de pomme', categoryName: 'Boissons non alcoolisées', unit: 'bouteille(s)' },
  { name: 'Côte de bœuf', categoryName: 'Boucherie', unit: 'pièce(s)' },
  { name: 'Poulet entier', categoryName: 'Boucherie', unit: 'pièce(s)' },
  { name: 'Steak haché', categoryName: 'Boucherie', unit: 'pièce(s)' },
  { name: 'Baguette', categoryName: 'Boulangerie', unit: 'article(s)' },
  { name: 'Croissants', categoryName: 'Boulangerie', unit: 'sachet(s)' },
  { name: 'Brioche', categoryName: 'Boulangerie', unit: 'article(s)' },
  { name: 'Vis', categoryName: 'Bricolage', unit: 'sachet(s)' },
  { name: 'Prise électrique', categoryName: 'Bricolage', unit: 'article(s)' },
  { name: 'Tournevis', categoryName: 'Bricolage', unit: 'article(s)' },
  { name: 'Pâté en croûte', categoryName: 'Charcuterie', unit: 'morceau(x)' },
  { name: 'Terrine de campagne', categoryName: 'Charcuterie', unit: 'morceau(x)' },
  { name: 'Boudin noir aux oignons', categoryName: 'Charcuterie', unit: 'g' },
  { name: 'Sel', categoryName: 'Condiments', unit: 'boite(s)' },
  { name: 'Poivre', categoryName: 'Condiments', unit: 'sachet(s)' },
  { name: 'Moutarde', categoryName: 'Condiments', unit: 'pot(s)' },
  { name: 'Ketchup', categoryName: 'Condiments', unit: 'tube(s)' },
  { name: 'Curry', categoryName: 'Condiments', unit: 'flacon(s)' },
  { name: 'Beurre', categoryName: 'Crémerie / Fromagerie', unit: 'plaquette(s)' },
  { name: 'Crème fraîche solide', categoryName: 'Crémerie / Fromagerie', unit: 'pot(s)' },
  { name: 'Lampe', categoryName: 'Décoration', unit: 'article(s)' },
  { name: 'Cadre de tableau', categoryName: 'Décoration', unit: 'article(s)' },
  { name: 'Allumettes', categoryName: 'Droguerie', unit: 'boite(s)' },
  { name: 'Bougie', categoryName: 'Droguerie', unit: 'article(s)' },
  { name: 'Cafetière', categoryName: 'Electroménager', unit: 'article(s)' },
  { name: 'Grille pain', categoryName: 'Electroménager', unit: 'article(s)' },
  { name: 'Stylos', categoryName: 'Fournitures scolaires', unit: 'sachet(s)' },
  { name: 'Cahier', categoryName: 'Fournitures scolaires', unit: 'article(s)' },
  { name: 'Feuilles', categoryName: 'Fournitures scolaires', unit: 'paquet(s)' },
  { name: 'Courgette', categoryName: 'Fruits / légumes', unit: 'pièce(s)' },
  { name: 'Tomates', categoryName: 'Fruits / légumes', unit: 'kg' },
  { name: 'Céleris', categoryName: 'Fruits / légumes', unit: 'branche(s)' },
  { name: 'Chips (petit sachet)', categoryName: 'Apéritifs', unit: 'sachet(s)' },
  { name: 'Cacahuètes', categoryName: 'Apéritifs', unit: 'sachet(s)' },
  { name: 'Olives', categoryName: 'Apéritifs', unit: 'barquette(s)' },
  { name: 'Mars', categoryName: 'Confiserie', unit: 'paquet(s)' },
  { name: 'Sucettes', categoryName: 'Confiserie', unit: 'sachet(s)' },
  { name: 'Haricots verts', categoryName: 'Conserves', unit: 'boite(s)' },
  { name: 'Petits pois', categoryName: 'Conserves', unit: 'boite(s)' },
  { name: 'Cœur de palmier', categoryName: 'Conserves', unit: 'boite(s)' },
  { name: 'Shampoing', categoryName: 'Hygiène / Santé', unit: 'tube(s)' },
  { name: 'Déodorant', categoryName: 'Hygiène / Santé', unit: 'article(s)' },
  { name: 'Gel douche', categoryName: 'Hygiène / Santé', unit: 'tube(s)' },
  { name: 'Souris', categoryName: 'Informatique / multimédia', unit: 'unité(s)' },
  { name: 'Carte SD', categoryName: 'Informatique / multimédia', unit: 'unité(s)' },
  { name: 'Ficelle', categoryName: 'Jardinage', unit: 'unité(s)' },
  { name: 'Graines de radis', categoryName: 'Jardinage', unit: 'sachet(s)' },
  { name: 'Puzzle', categoryName: 'Jouets', unit: 'article(s)' },
  { name: 'Lait', categoryName: 'Laiterie', unit: 'pack(s)' },
  { name: 'Oeufs', categoryName: 'Laiterie', unit: 'boite(s)' },
  { name: 'Farine', categoryName: 'Matières premières', unit: 'sachet(s)' },
  { name: 'Sucre en poudre', categoryName: 'Matières premières', unit: 'boite(s)' },
  { name: 'Miel', categoryName: 'Matières premières', unit: 'pot(s)' },
  { name: 'Livre', categoryName: 'Papeterie', unit: 'article(s)' },
  { name: 'Carte postale', categoryName: 'Papeterie', unit: 'article(s)' },
  { name: 'Sandwich', categoryName: 'Pause déjeuné', unit: 'paquet(s)' },
  { name: 'Salade de lentilles', categoryName: 'Pause déjeuné', unit: 'barquette(s)' },
  { name: 'Biscottes', categoryName: 'Petit déjeuné', unit: 'paquet(s)' },
  { name: 'Avoine', categoryName: 'Petit déjeuné', unit: 'boite(s)' },
  { name: 'Sardine', categoryName: 'Poissonnerie', unit: 'kg' },
  { name: 'Crevettes', categoryName: 'Poissonnerie', unit: 'g' },
  { name: 'Saumon', categoryName: 'Poissonnerie', unit: 'morceau(x)' },
  { name: 'Bloc WC', categoryName: 'Produits d’entretien', unit: 'boite(s)' },
  { name: 'Nettoyant sol', categoryName: 'Produits d’entretien', unit: 'bidon(s)' },
  { name: 'Sauce soja', categoryName: 'Produits du monde', unit: 'bouteille(s)' },
  { name: 'Wraps', categoryName: 'Produits du monde', unit: 'sachet(s)' },
  { name: 'Céréales', categoryName: 'Produits en vrac / au poids', unit: 'g' },
  { name: 'Lessive', categoryName: 'Produits en vrac / au poids', unit: 'kg' },
  { name: 'Lardon', categoryName: 'Produits frais industriels', unit: 'barquette(s)' },
  { name: 'Jambon', categoryName: 'Produits frais industriels', unit: 'barquette(s)' },
  { name: 'Pâte feuilletée', categoryName: 'Produits frais industriels', unit: 'rouleau(x)' },
  { name: 'Lait en poudre bébé', categoryName: 'Puériculture', unit: 'boite(s)' },
  { name: 'Biberon', categoryName: 'Puériculture', unit: 'article(s)' },
  { name: 'Petit pot', categoryName: 'Puériculture', unit: 'pot(s)' },
  { name: 'Chaussures', categoryName: 'Sport / Loisirs', unit: 'article(s)' },
  { name: 'Vélo', categoryName: 'Sport / Loisirs', unit: 'article(s)' },
  { name: 'Haricots verts', categoryName: 'Surgelés', unit: 'sachet(s)' },
  { name: 'Pizza', categoryName: 'Surgelés', unit: 'pièce(s)' },
  { name: 'Glace', categoryName: 'Surgelés', unit: 'pot(s)' },
  { name: 'Café en grains', categoryName: 'Thé / café', unit: 'sachet(s)' },
  { name: 'Thé à la mure', categoryName: 'Thé / café', unit: 'boite(s)' },
  { name: 'Café en capsules', categoryName: 'Thé / café', unit: 'paquet(s)' },
  { name: 'Paella', categoryName: 'Traiteur', unit: 'kg' },
  { name: 'Couscous', categoryName: 'Traiteur', unit: 'kg' },
  { name: 'Louche', categoryName: 'Ustensiles de cuisine', unit: 'article(s)' },
  { name: 'Marmite', categoryName: 'Ustensiles de cuisine', unit: 'article(s)' },
  { name: 'Grande assiette', categoryName: 'Vaisselle / Art de la table', unit: 'pièce(s)' },
  { name: 'Verre à pied', categoryName: 'Vaisselle / Art de la table', unit: 'pièce(s)' },
  { name: 'Désodorisant', categoryName: 'Véhicules (Auto / moto)', unit: 'article(s)' },
  { name: 'Huile', categoryName: 'Véhicules (Auto / moto)', unit: 'bidon(s)' },
  { name: 'Chaussettes', categoryName: 'Vêtements', unit: 'article(s)' },
  { name: 'Caleçon', categoryName: 'Vêtements', unit: 'article(s)' },
];

export const DEFAULT_STORE_NAMES = [
  'Leclerc', 'Carrefour', 'Auchan', 'Super U', 'Intermarché', 'Monoprix', 'Lidl', 'Aldi'
];

export const DEFAULT_UNITS = [
    'Aucune',
    'article(s)',
    'barquette(s)', 
    'bâton(s)',
    'bidon(s)',
    'boite(s)', 
    'botte(s)',
    'bouteille(s)',
    'branche(s)',
    'brique(s)',
    'cl', 
    'colis(s)',
    'filet(s)', 
    'fiole(s)',
    'flacon(s)',
    'fut(s)',
    'g', 
    'kg', 
    'L', 
    'morceau(x)',
    'pack(s)',
    'paquet(s)', 
    'pièce(s)', 
    'plaquette(s)',
    'pot(s)',
    'rouleau(x)',
    'sac(s)',
    'sachet(s)',
    'tranche(s)',
    'tube(s)',
    'unité(s)'
];

export const ICONS_LIST = [
  'Apple', 'Banana', 'Beef', 'Beer', 'Book', 'Box', 'Briefcase', 'Brush', 'CakeSlice', 'Candy',
  'Car', 'Carrot', 'ChefHat', 'Cheese', 'Chopsticks', 'Cigarette', 'CircleDollarSign', 'Coffee', 'Cookie',
  'Croissant', 'CupSoda', 'Cylinder', 'Dog', 'Droplet', 'Dumbbell', 'Fish', 'Flower', 'Gamepad2', 'Gift',
  'GlassWater', 'Globe', 'Hammer', 'HeartPulse', 'Home', 'IceCream', 'Key', 'Lamp', 'Laptop',
  'Leaf', 'Lightbulb', 'Milk', 'Package', 'Paintbrush', 'Pencil', 'Pepper', 'Pizza', 'Plug',
  'Ruler', 'Sandwich', 'Sausage', 'Scale', 'Scissors', 'Shirt', 'ShoppingBasket', 'ShoppingCart',
  'Smartphone', 'Snowflake', 'Sparkles', 'SprayCan', 'Store', 'Sun', 'Thermometer', 'Tv',
  'Umbrella', 'Utensils', 'Wheat', 'Wine', 'Wrench', 'Baby'
];

// Palettes definitions for Tailwind Variable Injection
export const THEME_PALETTES: Record<ThemeColor, Record<number | string, string>> = {
  blue: { // Indigo
    50: '#eef2ff', 100: '#e0e7ff', 200: '#c7d2fe', 300: '#a5b4fc', 400: '#818cf8',
    500: '#6366f1', 600: '#4f46e5', 700: '#4338ca', 800: '#3730a3', 900: '#312e81', 950: '#1e1b4b'
  },
  bordeaux: { // Rose-ish / Red
    50: '#fff1f2', 100: '#ffe4e6', 200: '#fecdd3', 300: '#fda4af', 400: '#fb7185',
    500: '#f43f5e', 600: '#e11d48', 700: '#be123c', 800: '#9f1239', 900: '#881337', 950: '#4c0519'
  },
  yellow: { // Amber
    50: '#fffbeb', 100: '#fef3c7', 200: '#fde68a', 300: '#fcd34d', 400: '#fbbf24',
    500: '#f59e0b', 600: '#d97706', 700: '#b45309', 800: '#92400e', 900: '#78350f', 950: '#451a03'
  },
  orange: { // Orange
    50: '#fff7ed', 100: '#ffedd5', 200: '#fed7aa', 300: '#fdba74', 400: '#fb923c',
    500: '#f97316', 600: '#ea580c', 700: '#c2410c', 800: '#9a3412', 900: '#7c2d12', 950: '#431407'
  },
  mauve: { // Violet/Fuchsia mix -> Violet
    50: '#f5f3ff', 100: '#ede9fe', 200: '#ddd6fe', 300: '#c4b5fd', 400: '#a78bfa',
    500: '#8b5cf6', 600: '#7c3aed', 700: '#6d28d9', 800: '#5b21b6', 900: '#4c1d95', 950: '#2e1065'
  },
  green: { // Emerald
    50: '#ecfdf5', 100: '#d1fae5', 200: '#a7f3d0', 300: '#6ee7b7', 400: '#34d399',
    500: '#10b981', 600: '#059669', 700: '#047857', 800: '#065f46', 900: '#064e3b', 950: '#022c22'
  }
};

export const THEME_DISPLAY_DATA: Record<ThemeColor, { label: string, color: string }> = {
    blue: { label: 'Bleu', color: '#4f46e5' },
    bordeaux: { label: 'Bordeaux clair', color: '#e11d48' },
    yellow: { label: 'Jaune clair', color: '#d97706' },
    orange: { label: 'Orange clair', color: '#ea580c' },
    mauve: { label: 'Mauve clair', color: '#7c3aed' },
    green: { label: 'Vert clair', color: '#059669' },
};

export const FONT_SIZES: Record<AppFontSize, { label: string, value: string }> = {
  small: { label: 'Petite', value: '87.5%' },   // ~14px
  medium: { label: 'Moyenne', value: '100%' },  // 16px
  large: { label: 'Grande', value: '115%' }     // ~18.4px
};
